// <auto-generated />
namespace EntityFramework_Sample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change940819 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change940819));
        
        string IMigrationMetadata.Id
        {
            get { return "201511100918508_change940819"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
